const paintings = [
  {
    id: 1,
    title: "Buttery Bouquet",
    theme: "flowers",
    image: "images/paintings/buttery-bouquet-clean.webp",
    images: ["images/paintings/buttery-bouquet-clean.webp", "images/paintings/buttery-bouquet.webp"],
    sold: false,
    size: "9 × 12 in.",
    medium: "Acrylic on stretched canvas",
    price: "$300.00",
    blurb: "Based on a photo I found on Instagram. It's a favorite of mine.",
    description: "Acrylic on stretched canvas, 9 × 12 in. A bouquet of buttery yellow and white flowser with the occasional orange and pink."
  },
  {
    id: 2,
    title: "Chicken Little",
    theme: "animals",
    image: "images/paintings/chicken-little-clean.webp",
    // Add more images here for the collage layout, e.g.:
    // images: ["images/paintings/chicken-little.webp", "images/paintings/chicken-little-2.webp", "images/paintings/chicken-little-3.webp"],
    images: ["images/paintings/chicken-little-clean.webp", "images/paintings/chicken-little-1.webp", "images/paintings/chicken-little-2.webp", "images/paintings/chicken-little-3.webp"],
    sold: false,
    size: "8 × 10 in.",
    medium: "Acrylic on stretched canvas",
    price: "$250.00",
    blurb: "Chickens are fun to paint. One of the first paintings that gave me real joy to paint was a little brood of chickens. When I found this guy in a pile of magazine clippings at the studio where I paint, I got right to it.",
    description: "Acrylic on stretched canvas, 8 × 10 in. A fuzzy baby white chicken in a sea of hay."
  },
  {
    id: 3,
    title: "For Linda",
    theme: "flowers",
    image: "images/paintings/for-linda-grid.webp",
    images: ["images/paintings/for-linda-clean.webp", "images/paintings/for-linda.webp", "images/paintings/for-linda-home.webp"],
    sold: true,
    size: "9 × 12 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "This sits on my Nana's wall in her beautiful kitchen. She says she has her coffee with it in the morning and that makes me so happy.",
    description: "Acrylic on stretched canvas, 9 × 12 in. A bouquet of colorful flowers with lots of sunlight poking through."
  },
  {
    id: 4,
    title: "Cold Cows",
    theme: "animals",
    image: "images/paintings/cold-cows.webp",
    images: ["images/paintings/cold-cows.webp"],
    sold: true,
    size: "18 × 24 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "I was drawn to this image from instagram. I'd painted chickens, so why not cows? Conveying the snow and cold was challenging. I almost gave up on this one a few times. One of my painting classmates took it home the same day I finished it which was really thrilling!",
    description: "Acrylic on stretched canvas, 18 × 24 in. Eight brown and black cows, grazing on a hill covered in grass and some snow."
  },
  {
    id: 5,
    title: "In the Window",
    theme: "flowers",
    image: "images/paintings/in-the-window-clean.webp",
    images: ["images/paintings/in-the-window-clean.webp", "images/paintings/in-the-window.webp"],
    sold: false,
    size: "12 × 16 in.",
    medium: "Acrylic on stretched canvas",
    price: "$500.00",
    blurb: "Another Instagram photo turned into a painting. It's fun painting against a dark background. This one was finished at home at the beginning of some turmoil in the world and at home. Zoning out with some paint brushes and beautiful flowers was mental medicine.",
    description: "Acrylic on stretched canvas, 12 × 16 in. Peach, pink and dark rose bouqeut sitting on a windowsill."
  },
  {
    id: 6,
    title: "Italian Sun",
    theme: "structures",
    image: "images/paintings/italian-sun-clean.webp",
    images: ["images/paintings/italian-sun-clean.webp", "images/paintings/italian-sun.webp"],
    sold: false,
    size: "36 × 60 in.",
    medium: "Acrylic on stretched canvas",
    price: "$2,000.00",
    blurb: "In the studio where I paint, the group teases me for painting smaller and smaller. So I challenged myself to a larger canvas. Based on a photo taken by my painting instructor.",
    description: "Acrylic on stretched canvas, 9 × 12 in. Not flattering. Honest, maybe."
  },
  {
    id: 7,
    title: "Light in the Corner",
    theme: "flowers",
    image: "images/paintings/light-in-the-corner-clean.webp",
    images: ["images/paintings/light-in-the-corner-clean.webp", "images/paintings/light-in-the-corner.webp"],
    sold: true,
    size: "8 × 10 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "This painting sold at our first ever student show. I was so excited... but also a little sad to let it go. One of the best moments working on this was adding the glimmer on the vase. One little brush stroke finished the painting.",
    description: "Acrylic on stretched canvase, 8 × 10 in. A bouquet of blush, orange and yellow and warm pink roses in a vase sitting in a corner."
  },
  {
    id: 8,
    title: "Little Pears",
    theme: "food",
    image: "images/paintings/little-pears-grid.webp",
    images: ["images/paintings/little-pears-clean.webp", "images/paintings/little-pears.webp", "images/paintings/the-show.webp",],
    sold: false,
    size: "8 × 6 in.",
    medium: "Acrylic on stretched canvas",
    price: "$75.00",
    blurb: "I had been working on a different painting and got disgusted. Picked up a photo of pears and got to work. The finished piece sits in a vintage music stand in our dining room... but sometimes wanders into cozy settings with our cat.",
    description: "Acrylic on stretched canvas, 8 × 6 in. Three green pears, framed such that they are bleeding off the edges."
  },
  {
    id: 9,
    title: "Cows on the Green",
    theme: "animals",
    image: "images/paintings/cows-on-the-green-clean.webp",
    images: ["images/paintings/cows-on-the-green-clean.webp", "images/paintings/cows-on-the-green.webp"],
    sold: true,
    size: "8 × 10 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "I had success with my first cows, so I painted more. These guys are now hanging with my in-laws.",
    description: "Acrylic on stretched canvas, 8 × 10 in. A bunch of cows, lounging in a sea of green grass."
  },
  {
    id: 10,
    title: "Lots of Lemons",
    theme: "food",
    image: "images/paintings/lots-of-lemons-grid.webp",
    images: ["images/paintings/lots-of-lemons.webp"],
    sold: true,
    size: "12 × 16 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "This one took me forever. I just kept painting over the lemons trying to get to something I couldn't find, so I gave up. I brought it home and a friend of a friend saw it and loved it. Go figure. By the way, this is a work-in-progress photo. It's the only one I have.",
    description: "Acrylic on stretched canvas, 12 × 16 in. Close up of a bunch of yellow lemons in a basket."
  },
  {
    id: 11,
    title: "Pears Well",
    theme: "food",
    image: "images/paintings/pears-well-clean.webp",
    images: ["images/paintings/pears-well-clean.webp", "images/paintings/pears-well.webp"],
    sold: false,
    size: "9 × 12 in.",
    medium: "Acrylic on stretched canvas",
    price: "$300.00",
    blurb: "This painting is based on an image in a really beautiful cookbook by Aran Goyoaga. Often, I start a painting with the intention of being free and loose - but then my brain wants to paint exactly what I see. Someday I'll learn how to do a better job of battling my basic instincts but in this case, I'm ok with the result.",
    description: "Acrylic on stretched canvas, 9 × 12 in. Portrait of pears, one in focus in front."
  },
  {
    id: 12,
    title: "Quiet Bouquet",
    theme: "flowers",
    image: "images/paintings/quiet-bouquet-clean.webp",
    images: ["images/paintings/quiet-bouquet-clean.webp", "images/paintings/quiet-bouquet.webp"],
    sold: false,
    size: "8 × 10 in.",
    medium: "Acrylic on stretched canvas",
    price: "$200.00",
    blurb: "This little painting feels like a quiet moment.",
    description: "Acrylic on stretched canvas, 8 × 10 in. Bouquet of flowers in a cream vase."
  },
  {
    id: 13,
    title: "Go to There",
    theme: "structures",
    image: "images/paintings/go-to-there-clean.webp",
    images: ["images/paintings/go-to-there-clean.webp"],
    sold: false,
    size: "12 × 12 in.",
    medium: "Acrylic on stretched canvas",
    price: "$350.00",
    blurb: "There are several paintings under this one. I can get really irritated with this whole painting business but my husband reminds me to “play” and I snap out of it.",
    description: "Acrylic on stretched canvas, 12 × 12 in. Old cottage on a hill."
  },
  {
    id: 14,
    title: "Bursting Bouquet",
    theme: "flowers",
    image: "images/paintings/bursting-bouquet-clean.webp",
    images: ["images/paintings/bursting-bouquet-clean.webp", "images/paintings/bursting-bouquet.webp"],
    sold: false,
    size: "8 × 10 in.",
    medium: "Acrylic on stretched canvas",
    price: "$350.00",
    blurb: "Lots of colors and lots of flowers. Sometimes, when I glance at this one, I really love it. Then other times I want to paint over it.",
    description: "Acrylic on stretched canvas, 8 × 10 in. Lots of colorful flowers bursting in all directions in a short (barely visible) vase."
  },
  {
    id: 15,
    title: "From Shore",
    theme: "water",
    image: "images/paintings/from-shore-clean.webp",
    images: ["images/paintings/from-shore-clean.webp"],
    sold: false,
    size: "8 × 8 in.",
    medium: "Acrylic on stretched canvas",
    price: "$150.00",
    blurb: "I'm frequently trying to figure out how I want to depict water in my paintings. I like how this turned out but I have no idea if I'll be able to replicate it.",
    description: "Acrylic on stretched canvas, 8 × 8 in. Looking out at a body of water from the edge of a rocky inlet."
  },
  {
    id: 16,
    title: "The Boat",
    theme: "water",
    image: "images/paintings/the-boat.webp",
    images: ["images/paintings/the-boat.webp", "images/paintings/the-boat-framed.webp"],
    sold: true,
    size: "8 × 6 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "Some of my favorite people on the planet have a beautiful home in Traverse City. This is their boat. I painted it for them and gave it to them because I love them with all my heart.",
    description: "Acrylic on stretched canvas, 8 × 6 in. A boat at the end of a dock."
  },
  {
    id: 17,
    title: "First Sale Chickens",
    theme: "animals",
    image: "images/paintings/chickens.webp",
    images: ["images/paintings/chickens.webp", "images/paintings/chickens-on-the-easel.webp"],
    sold: true,
    size: "8 × 6 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "This was my second painting. I saw these chickens in a magazine cut-out and, after a few false starts with the composition, it took off and was a great deal of fun to paint. I shared a pic of my progress with a good friend who immediately asked to have it. That was my first sale!",
    description: "Acrylic on stretched canvas, 8 × 6 in. Chickens and chicks frolicking."
  },
  {
    id: 18,
    title: "Jewett House",
    theme: "structures",
    image: "images/paintings/jewett-house-grid.webp",
    images: ["images/paintings/jewett-house.webp", "images/paintings/the-show.webp"],
    sold: true,
    size: "8 × 6 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "This one happened quick. It was (once again) started after a particularly grueling battle with a different painting. I picked it out from the pile of magazing clippings our teacher provides for inspiration and got to work. It flowed right away. Amazing how starting a different project can reset ones brain!",
    description: "Acrylic on stretched canvas, 8 × 6 in. A sun-drenched view of Jewett house."
  },
  {
    id: 19,
    title: "Marilyn Swimming",
    theme: "people",
    image: "images/paintings/marilyn-swimming-grid.webp",
    images: ["images/paintings/marilyn-swimming-framed.webp", "images/paintings/the-show.webp"],
    sold: false,
    size: "9 × 12 in.",
    medium: "Acrylic on stretched canvas",
    price: "$800.00",
    blurb: "This one is a painting of a photograph I really love by Richard Miller of Marilyn Monroe (1946). The photo is out of my reach to purchase, so I painted it. It's a bit pricier because it is already framed.",
    description: "Acrylic on stretched canvas, 8 × 6 in. Marylin."
  },
  {
    id: 20,
    title: "The Dude",
    theme: "animals",
    image: "images/paintings/the-dude-grid.webp",
    images: ["images/paintings/the-dude.webp", "images/paintings/the-dude-in-progress.webp"],
    sold: true,
    size: "9 × 9 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "The Dude is the Dude because he IS the dude. I painted this for his people (who I love) and it really ties the room together, man.",
    description: "Acrylic on stretched canvas, 9 × 9 in. Close-cropped portrait of a cute dog."
  },
  {
    id: 21,
    title: "Wee Sunflowers",
    theme: "flowers",
    image: "images/paintings/wee-sunflowers-grid.webp",
    images: ["images/paintings/the-dude.webp", "images/paintings/the-dude-in-progress.webp"],
    sold: false,
    size: "6 × 6 in.",
    medium: "Acrylic on stretched canvas",
    price: "$75.00",
    blurb: "This wee painting made me realize that sometimes, the smaller you paint, the harder it gets. It was still fun to work through.",
    description: "Acrylic on board, 6 × 6 in. Vase of sunflowers next to baskets of hay."
  },
  {
    id: 22,
    title: "CoCo",
    theme: "animals",
    image: "images/paintings/coco-grid.webp",
    images: ["images/paintings/coco.webp"],
    sold: true,
    size: "20 × 36 in.",
    medium: "Acrylic on stretched canvas",
    price: null,
    blurb: "Our cat. She rescued us during Covid and she will forever belong to my daughter but she makes all of us happy, even if she's nuts.",
    description: "Acrylic on board, 20 × 36 in. Picture of calico cat with black background."
  }   
];
